### ISSUE TITLE
Not compatible with new voyager version.

### ISSUE THREAD

**Issue by Stormiix** [pvtl/voyager-frontend#40]
the-control-group/voyager#3836

broke the code during installation here:

` Symfony\Component\Debug\Exception\FatalErrorException  : Trait 'TCG\Voyager\Traits\HasRelationships' not found at 
vendor\pvtl\voyager-pages\src\Page.php:12`

**Comment by noerarief23** [comment]
I have same issue.

![image](https://user-images.githubusercontent.com/5919917/50603535-67061280-0eed-11e9-98a3-14cf854cd070.png)

**Comment by markxxv** [comment]
HasRelationships trait has been removed from 1.1.11 [the-control-group/voyager/issues/3861](https://github.com/the-control-group/voyager/issues/3861)

need to update the Page model

**Comment by noerarief23** [comment]
you can use tcg/voyager:v1.1.10.
that still work with voyager-frontend

**Comment by abunour22** [comment]
Just download this file 👍 
https://github.com/the-control-group/voyager/blob/1.0/src/Traits/HasRelationships.php

**Comment by neko** [comment]
i've created temporary patched forks that you can include in your composer.json under `repositories`

        "voyager-pages": {
            "type": "vcs",
            "url": "https://github.com/neko/voyager-pages"
        },
        "voyager-blog": {
            "type": "vcs",
            "url": "https://github.com/neko/voyager-blog"
        }

**Comment by geekz-reno** [comment]
> i've created temporary patched forks that you can include in your composer.json under `repositories`
> 
> ```
>     "voyager-pages": {
>         "type": "vcs",
>         "url": "https://github.com/neko/voyager-pages"
>     },
>     "voyager-blog": {
>         "type": "vcs",
>         "url": "https://github.com/neko/voyager-blog"
>     }
> ```
> These are the dependencies that are causing the error.

hi neko, i copying this line, run composer update and the problem still exist,

**Comment by mcnamee** [comment]
This has been resolved in the latest release

**Comment by nathan-io** [comment]
@mcnamee 

Are you sure?

I have a broken staging site right now after a composer update. We had v2.2 installed.

I rolled back to 1.1.11, same error. Then I saw that it still existed in 1.1.10, and now the exception disappeared - but the data isn't coming through as expected 

The fault may lie in some of Voyager's controllers and views, but some clarification on this issue would be nice.
